### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by mdkocher** [paypal/paypal-ios#129]
The "PayPal Native Checkout" link in the readme results in a 404.

**Comment by scannillo** [comment]
👋 Hi @mdkocher - thank you so much for the feedback and for using the PayPal Mobile SDK.

The broken link was addressed [here](https://github.com/paypal/iOS-SDK/commit/52f1e15a3278f63d7c5946d638dbc569a0ca2d10). For any other suggestions or questions that come up, feel free to open another GitHub issue!
