### ISSUE TITLE
APIClient can't get the ClientID

### ISSUE THREAD

**Issue by laurentbourg** [paypal/paypal-ios#145]
In a native checkout flow. Turning off the cache resolves the issue. This used to work fine.

**Comment by scannillo** [comment]
Hi @laurentbourg - thanks for raising this issue to us. We'll need some more details in order to understand the issue:

- Environment:
- SDK version you're using:
- Describe the bug:
- Steps to reproduce:
- Expected behavior:

**Comment by laurentbourg** [comment]
> Hi @laurentbourg - thanks for raising this issue to us. We'll need some more details in order to understand the issue:
> 
> * Environment:
> * SDK version you're using:
> * Describe the bug:
> * Steps to reproduce:
> * Expected behavior:

Hey @scannillo thanks for getting back to me, this is running on a physical device iPhone XR iOS version 15.4.1 using the latest iPayPal OS-SDK (current main branch), Xcode 14.2. I am just initializing a PayPal client in SwiftUI, creating an order on the server side (intent is CAPTURE) and getting the PayPal order id from it, then constructing with it on the front end a PayPalNativeCheckoutRequest(orderID: paypal_orderID) and then await payPalClient?.start(request: request). 

The sheet does not get pulled and the log complain that there is no client id and to contact PayPal support.

Tracing the problem leads to the url cache returning nothing for the client id, turning off the cache (boolean flag) resolves the issue.

This used to work perfectly.

Laurent

**Comment by scannillo** [comment]
Hi Laurent - ticket DTNOR-947 will be used for tracking internally. We will keep you posted!

**Comment by laurentbourg** [comment]
Great thank you

**Comment by scannillo** [comment]
👋 Hi @laurentbourg - I am unable to replicate this issue. Can you please try the latest release 0.0.8 and report back if you still have the issue?

**Comment by laurentbourg** [comment]
Hello thanks for looking into this, will do.

**Comment by scannillo** [comment]
Also, is this happening in `sandbox`, `live` or both? I am currently not able to replicate in `sandbox`.

**Comment by laurentbourg** [comment]
This is in sandbox. Will make sure I get the latest release and will follow-up.

**Comment by scannillo** [comment]
👋 I am going to close this issue as we're no longer able to replicate. Wipe your device, and re-run the SDK.

If the issue still persists, please re-open this issue!

**Comment by doktorlorenzo** [comment]
I propose reopening this, i had exactly the same issue, had to wipe the simulator and reboot it and it worked, but took a while to figure it out.
- `.sandbox`
- `PayPal/PayPalNativePayments` v`0.0.8`

**Comment by scannillo** [comment]
👋 Hi @doktorlorenzo - thanks for commenting that you also had this issue, but that it was able to be resolved. We removing the Client ID caching layer entirely in #157. So if you point to `main` this issue should no longer exist. It will get released in the next version, as well!

Please do comment if you have further concerns!

**Comment by doktorlorenzo** [comment]
Ah, sounds great, thank you for your work
