### ISSUE TITLE
Credit card demo project not compiling

### ISSUE THREAD

**Issue by doktorlorenzo** [paypal/paypal-ios#164]
### PayPal SDK Version

0.0.8

### Environment

Sandbox

### Xcode Version

xcode 14.1

### OS Version & Device

any

### Integration type

Swfit Package Manager

### Development Processor

Intel

### Describe the bug

The Demo project to showcase the payments method usage is not compiling with a few import error on `PayPalWebPayments`, and `CorePayments`.

It seems particularly relevant since it is not possible from the documentation to understand what are the capabilities of the "Card" submodule (does it provide a Credit card form? validation?... etc) and how it integrates with the other submodules (a payment method picker? is there a unified delegate? etc..).

Thanks you for your time

### To reproduce

1. Checkout project
2. open Demo.xcodeproj
3. compile

### Expected behavior

The code compiles and runs.

**Comment by scannillo** [comment]
👋 Hi @doktorlorenzo - we are wrapping up our documentation that will live on www.developer.paypal.com which will definitely be easier to navigate to answer those questions you had mentions.

In the meantime, we have documented hosted in the repo [here](https://github.com/paypal/iOS-SDK/tree/main/docs). 

> It seems particularly relevant since it is not possible from the documentation to understand what are the capabilities of the "Card" submodule (does it provide a Credit card form? validation?... etc) and how it integrates with the other submodules (a payment method picker? is there a unified delegate? etc..).

Currently, the `CardPayments` module does not offer any credit card form UI. The only UI it offers is displaying and dismissing an `ASWebAuthenticationSession` if necessary for 3DS verification.

---

To run the Demo app, can you do `File > Packages > Resolve Package Versions` to make sure SPM properly syncs? 

We definitely should have instructions in our README or DEVELOPMENT files with steps on how to run the Demo. Ticket DTNOR-874 for internal tracking to complete this task.

**Comment by doktorlorenzo** [comment]
Hi, thank you for answering, ah great news about the new docs.

Sadly resolving package version or any other option i have regarding SPM does not help, `PayPalWebPayments` and other imported packages are still not found.

--
(May i hijack the topic one moment to ask you where can i find documentation on which fields are mandatory for the Credit card information? The Card object required only number, cvv and expiration, while name and billing address with zip code are optional. Testing in sandbaox with name and address set to nil seem to be valid as well, can i avoid requiring them in the UI? Or are there edge cases where they are required? I can't find this info in the RESTv2 API docs either)

Thank you

**Comment by scannillo** [comment]
👋 Hello @doktorlorenzo - I've [updated the README](https://github.com/paypal/paypal-ios/commit/c55371b90738fce3599403f3e12a62bc21edc8e6) with instructions on running our Demo application.

Please see this list of[ test card numbers](https://developer.paypal.com/docs/checkout/advanced/customize/3d-secure/test/) you can use. Please open a new issue for any follow up concerns, thank you!
