### ISSUE TITLE
User Login Persistence Feature

### ISSUE THREAD

**Issue by micjamroz** [paypal/paypal-ios#179]
### Is your feature request related to a problem? Please describe.

Does the current SDK support user login persistence? Users seem to be required to log in repeatedly, even within the same session. This can disrupt user workflow and possibly lead to frustration.

Edit: We are currently testing the web version because we require localisation, and the native version seems not to support it yet.

### Describe the solution you'd like.

I'm interested in knowing if there's a user login persistence feature in the SDK. This would allow users to log in once and remain authenticated for next payment. If this feature isn't already present, could you please share if there are plans to implement it in the future?

Your response would be greatly appreciated. Thank you.

**Comment by scannillo** [comment]
👋 Hi @mickoush - thank you for your valuable feedback.

For the PayPal web flow, we present an ASWebAuthenticationSession. Currently we have [`prefersEphemeralWebBrowserSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio) set to `true` ([here](https://github.com/paypal/paypal-ios/blob/00107331565548097c64294c6e8809536f0d6fab/Sources/CorePayments/WebAuthenticationSession.swift#L18)). If we set it to false instead, it should be able to persist log in details. Feel free to try it out on a repo fork, while we confirm that we're able to make this change.

As for localizations, the PayPalNativePayments module should indeed support them. Can you provide a more specific example of how it isn't working as expected with steps to replicate? A separate GitHub Issue would be best for this!

**Comment by micjamroz** [comment]
Hi @scannillo,

Thanks for the swift response and the recommended solution for user login persistence – much appreciated 👏.

Regarding the implementation, could you provide an estimated release date for version `0.0.10` with the proposed change? This will help us decide whether to await the official release or fork the repo for our needs.

On another note, about localization, I was referring to the ability for custom localizations within the app, distinct from the system-defined locale. However, it seems that the web version applies it fine, so we are good there for now.

Thanks again for your help and quick attention.

**Comment by scannillo** [comment]
> Regarding the implementation, could you provide an estimated release date for version 0.0.10 with the proposed change? This will help us decide whether to await the official release or fork the repo for our needs.

Yup - we have this fix in PR already (#181). Once it gets one more 👍, we can merge and release it. I would estimate ~1 week turnaround. You can stay tuned in that PR and by subscribing to the repo's releases.

**Comment by scannillo** [comment]
This fix was released in [0.0.10](https://github.com/paypal/paypal-ios/releases/tag/0.0.10). Thank you for bringing this to our attention!

If you come across any other issues with localizations please open a new bug report.
