### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by Cniklasson** [paypal/paypal-ios#250]
### PayPal SDK Version

1.1.0

### Environment

Sandbox

### Xcode Version

Xcode

### OS Version & Device

Iphone 14 & 17.2.1

### Integration type

Swfit Package Manager

### Development Processor

Both

### Describe the bug

Dear Developer,

We identified one or more issues with a recent delivery for your app, "Beliri" 1.0.1 (12). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

### To reproduce

PayPal Native payments followed this link

https://developer.paypal.com/docs/checkout/advanced/ios/

How to my developers move forward from here? We are stuck

### Expected behavior

To run smoothly 😒

### Screenshots

![IMG_4852](https://github.com/paypal/paypal-ios/assets/148633934/a672d439-7674-4042-aaca-186ebe7ed642)

**Comment by scannillo** [comment]
Hi @Cniklasson - our SDK doesn't use `UIWebView`. Are you sure you aren't using it elsewhere in your app, or maybe another 3rd party library that your app includes might use it?

**Comment by Cniklasson** [comment]
> Hi @Cniklasson - our SDK doesn't use `UIWebView`. Are you sure you aren't using it elsewhere in your app, or maybe another 3rd party library that your app includes might use it?

Here is the pods developers using.
So, PayPal Native Payments SDK is not using IUWebView. Hmm,  developers have hidden (commented #) some #pods. Already to find the issue. 

Do you have any advice to find where IUWebView can be? I just forward to the developers as i have bought app development from them. 

![IMG_4848](https://github.com/paypal/paypal-ios/assets/148633934/53e38079-b1de-44de-b1cf-92e94d78b35a)

**Comment by scannillo** [comment]
I recommend you grep your entire app/project for `UIWebView` which should indicate which library is using it, and then raise a GitHub issue with that respective library. You could also try isolated TestFlight builds to see if those trigger the `UIWebView` warning so you can narrow it down.

**Comment by Cniklasson** [comment]
This is the result -

apple@apples-MacBook-Pro-2 Nuvicci % grep -R UIWebView *
Binary file Resources/Paypal/libPayPalMobile.a matches
