### ISSUE TITLE
paypal-ios SDK Integration Conflict

### ISSUE THREAD

**Issue by tema-tian** [paypal/paypal-ios#280]
###

pod install errors when Braintree SDK is integrated with PayPal/FraudProtection

```
[!] The 'Pods-xxxx' target has frameworks with conflicting names: ppriskmagnes.xcframework.
```

**Comment by scannillo** [comment]
👋 Hi @tema-tian, can you please fill out our [issues template instead here](https://github.com/paypal/paypal-ios/issues/new?assignees=&labels=&projects=&template=bug_report.yml)? This way we can gather all of the appropriate data we need for triaging.

This is indeed a known issue and the temporary solution is to use either the Braintree SDK's DataCollector module _or_ the PayPal SDK's FraudProtection module, but not both. Both modules do the same thing. Please open a new issue following the template.
