### ISSUE TITLE
Paypal logo is missing on PayPalButton

### ISSUE THREAD

**Issue by sayalideopurkar** [paypal/paypal-ios#289]
### PayPal SDK Version

1.2.0

### Environment

Both

### Xcode Version

Xcode 15.3

### Integration type

CocoaPods

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

PayPal logo is missing when we integrate PayPal button in the UIKit app using Cocoapods. 

https://developer.paypal.com/docs/checkout/advanced/ios/#link-usepaypalbuttonsinyourui

### To reproduce

1. Integrate pod 'PayPal/PaymentButtons' 
2. Add below code 
`class MyViewController: UIViewController {
  lazy var payPalButton: PayPalButton = {
    let payPalButton = PayPalButton()
    payPalButton.addTarget(self, action: #selector(payPalButtonTapped), for: .touchUpInside)
    return payPalButton
  }()
  @objc func payPalButtonTapped() {
    // Insert your code here
  }
  override func viewDidLoad() {
    super.viewDidLoad()
    view.addSubview(payPalButton)
  }
}`

3. The button is displayed as empty box with no logo or label 

### Expected behavior

Paypal button with PayPal logo should be displayed as mentioned in the [documentation](https://developer.paypal.com/docs/checkout/advanced/ios/#link-createpaypalbutton)

### Screenshots

![Simulator Screenshot - iPhone 15 Pro - 2024-07-29 at 12 21 07](https://github.com/user-attachments/assets/3b84c227-8ca0-4c6d-83bd-7bba333b128e)

**Comment by jaxdesmarais** [comment]
Hello @sayalideopurkar -

This should be fixed in [version 1.3.0](https://github.com/paypal/paypal-ios/blob/main/CHANGELOG.md#130-2024-04-25). Though we always recommend updating to the latest version which is currently 1.4.0. Once you have a chance to update the SDK version will you let us know if you are still seeing this issue?

**Comment by sayalideopurkar** [comment]
Hello @jaxdesmarais 
Thank you for the reply, it works on 1.4.0
